### ISSUE TITLE
Question: Is there a way to not require a user to sign up?

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#471]
I am trying to make it so a user does not have to create an account when they download my app. Is this what the  [authenticationOptional](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L155)  property is used for? Or is this just not supported with Simperium?

**Comment by jleandroperez** [comment]
Hello there @lukegeiger,

The flag you've mentioned, `authenticationOptional`, allows the users to dismiss the login screen, if needed.

In order to Sync the local database, an account will be needed (that's a requirement). However, you could just delay the Signup sequence, until needed. In order to do so, you can just delay the [authenticate call](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L82), until it's needed.

Hope that helps!

**Comment by lukegeiger** [comment]
Gotcha. So let's say this is my use case




1. User downloads app and sees the sign up screen.

2. User chooses to not sign up, screen gets dismissed.

3. User inputs data stored via core data.

4. User decides to sign up.




After step 4, once I call authenicate, the core data database will sync everything correctly with simperium?



—
lg

**Comment by fredrocious** [comment]
@lukegeiger you must have an account to interact w/ simperium servers, but it doesn't necessarily mean your end users need to "log in". To talk w/ simperium you need a token, you could set up a server in the middle to do the authentication w/ simperium, and then have an API between your app and your server to pass the token to the app.

**Comment by jleandroperez** [comment]
@lukegeiger (Assuming that the user effectively signs up), yes, your flow is correct. Simperium has [this callback](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L56) that will get hit after a successful login.

Just in case: you could even delay step (2) until needed.

**Comment by lukegeiger** [comment]
Cool thanks for the help and quick responses guys!



—
lg

**Comment by jleandroperez** [comment]
@lukegeiger anytime!. Closing for now, if needed, please feel free to reopen.

Thanks Luke!
