### ISSUE TITLE
libSimperium.a was built for newer iOS version (7.0) than being linked (6.0)

### ISSUE THREAD

**Issue by katche70** [Simperium/simperium-ios#535]
I get 68 warnings. what can i do?

**Comment by jleandroperez** [comment]
Hello @katche70,

We've officially dropped support for iOS 6 (Simperium's Deployment Target is set to iOS 7) in [Release 0.8.4](https://github.com/Simperium/simperium-ios/releases/tag/v0.8.4).

Although *highly unadvisable* (since there are several known bugs), one possibility would be to just use an older version (0.8.3 would do the trick).

Hope that helps!
