### ISSUE TITLE
Wrong object type passed in the set method of an SPManagedObject

### ISSUE THREAD

**Issue by hyling** [Simperium/simperium-ios#540]
When Simperium tries to sync it's passing a `NSCFNumber` instead of a `NSDecimalNumber`.  This is an issue because I'm calling methods on a `NSDecimalNumber` that's defined in a ObjC category.

**Comment by jleandroperez** [comment]
Hello there,

`NSNumber` is actually a class cluster. Can you please provide a sample project demo-ing the issue you're experiencing?.

**Comment by hyling** [comment]
https://github.com/hyling/TestSimperiumCat  
Install app on device 1, create account & login,  tap + at top right.
Install app on device 2, create account & login, allow it to sync.  Crashes for me on Event.m line 18.

**Comment by jleandroperez** [comment]
Hello there @hyling, thanks for the sample project! (+ sorry about the late reply).

I'm afraid this glitch could be traced down to *json parsing* level / protocol level. Simperium itself doesn't make a difference between `Number` / `Decimal`, since everything, down to communications layer, everything is handled as json floats (and then parsed into `NSNumber`, by means of Apple's Json Parser.

Since this crash is triggered within a NSManagedObject setter, may i suggest a quick workaround perhaps?

```
- (void)setNumber:(NSDecimalNumber *)number {
    // This line will crash when sync to 2nd device
    if ([number isKindOfClass:[NSDecimalNumber class]] == false && [number isKindOfClass:[NSNumber class]]) {
        number = [NSDecimalNumber decimalNumberWithDecimal:number.decimalValue];
    }
```

I'm aware this is not 100% ideal, but for the time being, _should_ do the trick.

Again, thanks so much for the sample project!

**Comment by hyling** [comment]
@jleandroperez  Thanks for the suggestion.  I've been using what you suggested and it works.  Unfortunately I believe this issue could be a serious source of headaches because it has the potential to affect many Core Foundation methods as well.  Apple implements some methods as categories but they don't documented it.  I need to test this and I'll post my results when I do.
